### ISSUE TITLE
"NOT FOUND "completion behavior in menu when there is only matching 1 suggestion

### ISSUE THREAD

**Issue by frederic-loui** [holo-routing/holo-cli#6]
`holo-cli` does not have an expected behavior while completing word when there is only one matching solution.

Example with `interfaces` -> `interface` -> `<interface-name>` ->`ip<?>`:

Here completion 2 alternatives:
![multiple-selection-completion](https://github.com/holo-routing/holo-cli/assets/9639687/18cb875d-7ac6-4ef5-b196-01d013bcb2b8)

The last completion should complete to `ipv4`:
![last-selection-completion](https://github.com/holo-routing/holo-cli/assets/9639687/6a49cda6-4e88-4ad9-9515-42eb8450d8d9)

However, this is a general problem, when only there is one suggestion left in the completion list and that the cursor postion is right fater the matching word, the menu shows `NO RECORDS FOUND`. (It should be `NO RECORD FOUND` BTW)

**Comment by rwestphal** [comment]
Closed by #7
